### ISSUE TITLE
"errorMessage": "Cannot read property '0' of undefined",

### ISSUE THREAD

**Issue by tarun1982** [devcybiko/ses-catchall#3]
https://github.com/devcybiko/ses-catchall#test-it  -- When i am testing i am getting below error # 
Response
{
  "errorType": "TypeError",
  "errorMessage": "Cannot read property '0' of undefined",
  "trace": [
    "TypeError: Cannot read property '0' of undefined",
    "    at Runtime.handler (/var/task/index.js:69:45)",
    "    at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:73:25)"
  ]
}

Pls help me in fixing this issue.

**Comment by devcybiko** [comment]
it appears your code is getting called but not by SES. The line in question is

let sesMsg = JSON.parse(SNSEvent.Records[0].Sns.Message); log(JSON.stringify(sesMsg, null, 2));

the SNSEvent that is passed in appears to be empty. there is no 'Records' field which results in an error. My guess is your code was not invoked due to an SNS event
